### ISSUE TITLE
How to index files on another drive

### ISSUE THREAD

**Issue by craigwduckett** [Stremio/stremio-local-addon#21]
Hi,
is it possible to index files on another drive? As I have this git running under c:/my documents and it only searches my c drive. I then tried running it on my f drive but still only indexed my c drive.

**Comment by Ivshti** [comment]
on Windows, it scans all drives that are indexed by the windows search. Which, I think, excludes external drives. Is F external?

**Comment by craigwduckett** [comment]
Thanks, that was the problem. after adding f drive to my windows indexing it found all my files.
